---
general:
  vulnerabilities:
    # libretls vulnerability in alpine:3.15.1, currently there is no newer
    # alpine tag.
    - CVE-2022-0778
    # Authorization Bypass Through User-Controlled Key in GitHub repository
    # emicklei/go-restful prior to v3.8.0. We cannot do much about it as it's a
    # dependency of a dependency.
    - CVE-2022-1996
