apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "pod-image-swap-webhook.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "pod-image-swap-webhook.labels" . | nindent 4 }}
data:
  config.yaml: |
    {{- toYaml .Values.webhookConfig | nindent 4 }}
