{{- if eq .Values.kind "DaemonSet" -}}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "pod-image-swap-webhook.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "pod-image-swap-webhook.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "pod-image-swap-webhook.selectorLabels" . | nindent 6 }}
  template:
    {{- include "pod-image-swap-webhook.podTemplate" . | nindent 4 }}
{{- end }}
