apiVersion: v1
kind: Service
metadata:
  name: {{ include "pod-image-swap-webhook.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "pod-image-swap-webhook.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 443
      targetPort: webhook
      protocol: TCP
      name: webhook
    - port: 8080
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "pod-image-swap-webhook.selectorLabels" . | nindent 4 }}
